FROM instructure/rvm

WORKDIR /app

COPY imperium.gemspec Gemfile* /app/
COPY lib/imperium/version.rb /app/lib/imperium/version.rb

USER root
RUN chown -R docker:docker /app
USER docker

RUN /bin/bash -l -c "cd /app && bundle install"
COPY . /app

USER root
RUN chown -R docker:docker /app
USER docker

CMD /bin/bash -l -c "bundle exec wwtd --parallel"
