FROM instructure/rvm

WORKDIR /app

COPY imperium.gemspec Gemfile* /app/
COPY lib/imperium/version.rb /app/lib/imperium/version.rb

USER root
RUN chown -R docker:docker /app
USER docker

RUN /bin/bash -l -c "cd /app && rvm-exec 2.5 bundle install"
COPY . /app

USER root
RUN chown -R docker:docker /app
USER docker

CMD /bin/bash -l -c "rvm-exec 2.5 bundle exec wwtd"
