version: "2"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.ci
    links:
      - consul
    environment:
      IMPERIUM_CONSUL_HOST: "consul"
      IMPERIUM_CONSUL_PORT: 8500
      IMPERIUM_CONSUL_SSL: "false"

  consul:
    image: consul:0.7.2
    command: agent -dev -client 0.0.0.0 -datacenter imperium-dev -node imperium-consul -bootstrap
    environment:
      GOMAXPROCS: "2"
      VIRTUAL_PORT: 8500
